### ISSUE TITLE
Formula (4) Derivation

### ISSUE THREAD

**Issue by Katherine-Cao** [Intelligent-Computing-Lab-Yale/Rate-vs-Direct#2]
Hello, I don't understand the derivation of formula (4) in your paper, how to get the approximate gradient of the output spikes and the membrane potential？Thank you

**Comment by Katherine-Cao** [comment]
Hello, I have a question about the paper "RATE CODING OR DIRECT CODING". I don't understand the derivation of formula (4) in your paper, Does this formula (4) is directly set or derived？I don't know how to get this. Thank you

**Comment by lotusroot-kim** [comment]
Hello, Eq.4 is the usual "piece-wise linear" surrogate gradient function, it does not require derivation since Eq.4 is the definition itself. You can refer to previous SNN works -"Neftci, Emre O., Hesham Mostafa, and Friedemann Zenke. "Surrogate gradient learning in spiking neural networks: Bringing the power of gradient-based optimization to spiking neural networks." IEEE Signal Processing Magazine 36.6 (2019): 51-63."

**Comment by Katherine-Cao** [comment]
thank you for your answer
